Traceback (most recent call last):
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/psutil/_common.py", line 443, in wrapper
    ret = self._cache[fun]
AttributeError: 'Process' object has no attribute '_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/psutil/_common.py", line 446, in wrapper
    return fun(self)
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/psutil/_psosx.py", line 373, in _get_kinfo_proc
    ret = cext.proc_kinfo_oneshot(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(kinfo_proc), len == 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/psutil/__init__.py", line 361, in _init
    self.create_time()
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/psutil/__init__.py", line 714, in create_time
    self._create_time = self._proc.create_time()
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/psutil/_psosx.py", line 471, in create_time
    return self._get_kinfo_proc()[kinfo_proc_map['ctime']]
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/psutil/_psosx.py", line 351, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=43768)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/airflow/cli/cli_parser.py", line 52, in command
    return func(*args, **kwargs)
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/airflow/utils/cli.py", line 108, in wrapper
    return f(*args, **kwargs)
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 489, in webserver
    monitor_gunicorn(gunicorn_master_proc.pid)
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 454, in monitor_gunicorn
    ).start()
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 210, in start
    self._wait_until_true(
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 156, in _wait_until_true
    while not fn():
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 211, in <lambda>
    lambda: self.num_workers_expected == self._get_num_workers_running(),
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 150, in _get_num_workers_running
    workers = psutil.Process(self.gunicorn_master_proc.pid).children()
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/psutil/__init__.py", line 332, in __init__
    self._init(pid)
  File "/Users/mohammedtharzeez/.pyenv/versions/3.10.10/lib/python3.10/site-packages/psutil/__init__.py", line 373, in _init
    raise NoSuchProcess(pid, msg='process PID not found')
psutil.NoSuchProcess: process PID not found (pid=43768)
